"""create users events agenda items and bookings

Revision ID: 701d78ffded2
Revises:
Create Date: 2026-08-24 22:49:44.735211

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "701d78ffded2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("venue", sa.String(length=180), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("format IN ('in_person', 'online', 'hybrid')", name="ck_events_format"),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'cancelled')", name="ck_events_status"
        ),
        sa.CheckConstraint("capacity > 0", name="ck_events_positive_capacity"),
        sa.CheckConstraint("end_at > start_at", name="ck_events_valid_dates"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_city"), ["city"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_format"), ["format"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_start_at"), ["start_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_status"), ["status"], unique=False)

    op.create_table(
        "agenda_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("speaker", sa.String(length=120), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name="ck_agenda_items_valid_dates"),
        sa.CheckConstraint("position >= 0", name="ck_agenda_items_position"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agenda_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agenda_items_event_id"), ["event_id"], unique=False)

    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('confirmed', 'cancelled')", name="ck_bookings_status"),
        sa.CheckConstraint("quantity BETWEEN 1 AND 10", name="ck_bookings_quantity"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "event_id", name="uq_bookings_user_event"),
    )
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookings_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookings_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookings_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookings_user_id"))
        batch_op.drop_index(batch_op.f("ix_bookings_status"))
        batch_op.drop_index(batch_op.f("ix_bookings_event_id"))

    op.drop_table("bookings")
    with op.batch_alter_table("agenda_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agenda_items_event_id"))

    op.drop_table("agenda_items")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_status"))
        batch_op.drop_index(batch_op.f("ix_events_start_at"))
        batch_op.drop_index(batch_op.f("ix_events_owner_id"))
        batch_op.drop_index(batch_op.f("ix_events_format"))
        batch_op.drop_index(batch_op.f("ix_events_city"))
        batch_op.drop_index(batch_op.f("ix_events_category"))

    op.drop_table("events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
